openapi: 3.0.0
info:
  title: Wallet Core API
  description: Trust Wallet Core API wrapper and more.
  version: 0.0.0
servers:
  - url: http://127.0.0.1:3000
paths:
  /health:
    get:
      tags:
        - Health
      summary: Health
      description: This endpoint will check the readiness and liveness of the service.
      operationId: Health
      responses:
        204:
          description: No Content response.

  /v1/hdwallet:
    post:
      tags:
        - HDWallet
      summary: Create an HDWallet
      description: By using this endpoint, you can create an HDWallet using request parameters.
      operationId: CreateHDWallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateHDWalletRequest'
      responses:
        200:
          description: Response to creating an HDWallet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateHDWalletResponse'
        400:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/transaction:
    get:
      tags:
        - Transaction
      summary: Get Transaction Info
      description: By using this endpoint, you can retrieve the transaction info.
      operationId: GetTransactionInfo
      parameters:
        - name: symbol
          in: query
          schema:
            type: string
            example: BTC
        - name: transactionId
          in: query
          schema:
            type: string
            example: 'bbd4a06ba81cd97a8f1e7ab4fd9fea9f324f5d2c83c50de2b19d6f3dc7197c4d'
      responses:
        200:
          description: Response to getting the transaction info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransactionInfoResponse'
        400:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/wallet/transactions:
    get:
      tags:
        - Transaction
      summary: Get Wallet Transactions
      description: By using this endpoint, you can retrieve last 100 transactions of your wallet.
      operationId: GetWalletTransactions
      parameters:
        - name: symbol
          in: query
          schema:
            type: string
            example: ETH
        - name: walletId
          in: query
          schema:
            type: string
            example: '0xb3aafc07e4ea2a66866b2d2d1a8e28deee400770'
      responses:
        200:
          description: Response to getting the wallet transactions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWalletTransactionsResponse'
        400:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
          example:
            - Something Went Wrong!
    CreateHDWalletRequest:
      type: object
      properties:
        symbol:
          type: string
          example: BTC
        accountIndex:
          type: integer
          format: int64
          default: 0
          minimum: 0
          example: 0
        externalChain:
          type: integer
          format: int64
          default: 0
          minimum: 0
          example: 0
        addressIndex:
          type: integer
          format: int64
          default: 0
          minimum: 0
          example: 1
    CreateHDWalletResponse:
      type: object
      properties:
        address:
          type: string
          example: '0xb315B05d06f74b27D3869219f41119585Fcb8656'
        publicKey:
          type: string
          example: '04a6f1596c27229b369e92feab4345cabc6b057baadf53211650b27aa7f1b760f9d3f0cb892067c4b9a0aaa7464a9797aa805c77fdca73da49899c295f47355990'
        privateKey:
          type: string
          example: '3e421d9c54e97085b18dd39a9c9eee29eb3f9a289088a1b19ebbdc81e696a28a'
    GetTransactionInfoResponse:
      type: object
      properties:
        confirmed:
          type: boolean
          example: true
        confirmations:
          type: integer
          format: int64
          example: 26
        requireConfirmations:
          type: integer
          format: int64
          example: 10
        url:
          type: string
          example: 'https://blockchair.com/dogecoin/transaction/bbd4a06ba81cd97a8f1e7ab4fd9fea9f324f5d2c83c50de2b19d6f3dc7197c4d'
    GetWalletTransactionsResponse:
      type: array
      items:
        type: object
        properties:
          transactionHash:
            type: string
            example: '0xd7ce8996bc3b56d3c7e378acbd4529fdaaba87264efc3f128a5d3baa7533ec4d'
          timestamp:
            type: integer
            format: int64
            example: 1689163103
          balanceChange:
            type: integer
            format: float64
            example: -41.5
